volumes:
  hot-stocks:
    external: true
  jwtdown-db-data:
    external: true

services:
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
        - ./ghi:/app
    ports:
        - "3000:3000"
    environment:
        REACT_APP_API_HOST: http://localhost:8000
        HOST_OS: ${OS}
        NODE_ENV: development
        HOST: "0.0.0.0"
        CHOKIDAR_USEPOLLING: true # create-ui-app <= 5.x
        WATCHPACK_POLLING: true # create-ui-app >= 5.x

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      REACT_APP_SERVICE: http://localhost:3000
      ALPHAVANTAGE_SERVICE: https://www.alphavantage.co
      FMP_SERVICE: https://financialmodelingprep.com
      ALPHAVANTAGE_API_KEY: RDM3VKZSAAEPH920 # ${ALPHAVANTAGE_API_KEY}
      FMP_API_KEY: d9d102aa66e8530a6ae66e89468b5aa1 # ${FMP_API_KEY}
      DATABASE_URL: postgresql://hot-stocks:hot-stocks@db/hot-stocks
      WAIT_HOSTS: db:5432
      PORT: 8000
      SIGNING_KEY: b4rDKEvWf5TeGnENY7dTgP8nYldVpqixIb3cnWmt75o # ${SIGNING_KEY}
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  db:
    build:
      context: relational-data
      dockerfile: Dockerfile.dev
    volumes:
      - hot-stocks:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: hot-stocks
      POSTGRES_USER: hot-stocks
      POSTGRES_DB: hot-stocks
    ports:
      - "15432:5432"
