volumes:
  postgres-data:
    external: true
  mongo-data:
    external: true

services:
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
        - ./ghi:/app
    ports:
        - "3000:3000"
    environment:
        HOST_OS: ${OS}
        NODE_ENV: development
        HOST: "0.0.0.0"
  hot-stocks-api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      REACT_APP_FASTAPI_SERVICE: http://localhost:8000
      REACT_APP_THIRD_PARTY_SERVICE: https://www.alphavantage.co
      # DATABASE_URL: postgresql://postgres:password@postgres/hot_stocks
      DATABASE_URL: postgresql://hot_stocks:password@postgres/hot_stocks
        # change back to hot_stocks (instead of postgres) once alex can help
      WAIT_HOSTS: postgres:5432
      PORT: 8000
      # DATABASE_URL: mongodb://root:password@mongo
      # DATABASE_NAME: db-name
      # WAIT_HOSTS: mongo:27017

    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  postgres:
      build:
          context: ./relational-data
          dockerfile: ./Dockerfile.dev
      volumes:
          - postgres-data:/var/lib/postgresql/data
          # - ./relational-data/hot-stocks.sql:/docker-entrypoint-initdb.d/hot-stocks.sql
      environment:
          - POSTGRES_MULTIPLE_DATABASES=hot_stocks
          - POSTGRES_PASSWORD=test-databases
      ports:
          - 15432:5432
  # mongo:
  #   image: mongo:5
  #   volumes:
  #       - mongo-data:/data/db
  #   environment:
  #       MONGO_INITDB_ROOT_USERNAME: root
  #       MONGO_INITDB_ROOT_PASSWORD: password
